CREATE TABLE public.chatwoot_settings (
  id bigint generated by default as identity primary key,
  chatwoot_url text,
  account_id text,
  inbox_id text,
  api_token text,
  created_at timestamp with time zone default now() not null
);

ALTER TABLE public.chatwoot_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to access settings"
ON public.chatwoot_settings
FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- For simplicity without auth, we can allow anon access.
-- If you add login later, the policy above is better.
CREATE POLICY "Allow public access for now"
ON public.chatwoot_settings
FOR ALL
USING (true)
WITH CHECK (true);

-- Insert a default row to make updates easier
INSERT INTO public.chatwoot_settings (id, chatwoot_url, account_id, inbox_id, api_token)
VALUES (1, 'https://app.chatwoot.com', '', '', '');