CREATE TABLE public.ai_settings (
  id bigint generated by default as identity primary key,
  api_url text,
  api_key text,
  created_at timestamp with time zone default now() not null
);

ALTER TABLE public.ai_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access for now"
ON public.ai_settings
FOR ALL
USING (true)
WITH CHECK (true);

INSERT INTO public.ai_settings (id, api_url, api_key)
VALUES (1, 'https://multiappai-api.itmovnteam.com/api/v1/chat/completions', '');