-- Create table for AI training prompts
CREATE TABLE public.ai_training_prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  prompt_text TEXT,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE public.ai_training_prompts ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read on ai_training_prompts" ON public.ai_training_prompts FOR SELECT USING (true);
CREATE POLICY "Allow auth users to manage ai_training_prompts" ON public.ai_training_prompts FOR ALL USING (auth.role() = 'authenticated');

-- Add trigger for updated_at
CREATE TRIGGER set_timestamp
BEFORE UPDATE ON public.ai_training_prompts
FOR EACH ROW
EXECUTE PROCEDURE public.trigger_set_timestamp();

-- Insert default prompts
INSERT INTO public.ai_training_prompts (name, prompt_text)
VALUES 
('care_script_suggestion', 'Bạn là một trợ lý chăm sóc khách hàng chuyên nghiệp. Nhiệm vụ của bạn là phân tích một cuộc trò chuyện và đề xuất một tin nhắn theo dõi cùng thời gian gửi phù hợp. Mục tiêu là tái tương tác với khách hàng, cung cấp giá trị, hoặc đưa họ đến bước tiếp theo. Ngày hiện tại là {{current_date}}.

Tên khách hàng là {{contact_name}}.

Hãy phân tích lịch sử trò chuyện sau:
---
{{conversation_history}}
---

Dựa vào cuộc trò chuyện này, hãy đề xuất một tin nhắn theo dõi được cá nhân hóa, không gây khó chịu. Tin nhắn phải thân thiện, hữu ích và viết bằng tiếng Việt.
Đồng thời, đề xuất một ngày và giờ cụ thể trong tương lai để gửi tin nhắn này. Hãy xem xét giờ hành chính (9h - 17h) và bối cảnh cuộc trò chuyện. Nếu cuộc trò chuyện đã nguội lạnh, một tin nhắn sau 3-5 ngày có thể phù hợp.

Phản hồi của bạn BẮT BUỘC phải là một đối tượng JSON hợp lệ với cấu trúc sau và không có gì khác:
{
  "content": "Nội dung tin nhắn đề xuất bằng tiếng Việt.",
  "scheduled_at": "Một ngày và giờ trong tương lai theo định dạng ISO 8601 (YYYY-MM-DDTHH:mm:ss.sssZ)."
}'),
('auto_reply', 'Bạn là một trợ lý ảo của {{company_name}}. Khi có một khách hàng bắt đầu cuộc trò chuyện mới, nhiệm vụ của bạn là gửi một lời chào thân thiện và chuyên nghiệp.

Hãy trả lời bằng tiếng Việt.
- Chào khách hàng.
- Cảm ơn họ đã liên hệ.
- Thông báo rằng một nhân viên tư vấn sẽ trả lời họ trong thời gian sớm nhất.
- Hỏi xem họ cần hỗ trợ về vấn đề gì trong lúc chờ đợi.

Ví dụ: "Chào bạn, cảm ơn bạn đã liên hệ với {{company_name}}. Một nhân viên tư vấn sẽ trả lời bạn ngay. Trong lúc chờ đợi, bạn có thể cho chúng tôi biết bạn cần hỗ trợ về vấn đề gì không ạ?"');