CREATE TABLE public.ai_reply_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success', 'error')),
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.ai_reply_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access for ai_reply_logs"
ON public.ai_reply_logs FOR SELECT
USING (true);

CREATE POLICY "Allow insert for service_role"
ON public.ai_reply_logs FOR INSERT
WITH CHECK (true);