CREATE TABLE public.keyword_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  keyword TEXT,
  action_type TEXT NOT NULL,
  reply_content TEXT,
  creator_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

ALTER TABLE public.keyword_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access for authenticated users"
ON public.keyword_actions
FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');