-- Create ai_plan_logs table
CREATE TABLE public.ai_plan_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  plan_id BIGINT REFERENCES public.ai_plans(id) ON DELETE CASCADE NOT NULL,
  creator_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  prompt TEXT,
  response JSONB
);

-- Enable RLS
ALTER TABLE public.ai_plan_logs ENABLE ROW LEVEL SECURITY;

-- Create policies for secure access
CREATE POLICY "Allow team access for AI Plan logs" ON public.ai_plan_logs
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.ai_plans
    WHERE id = ai_plan_logs.plan_id
  )
);