-- Create the new table for AI plan templates
CREATE TABLE public.ai_plan_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    structure JSONB,
    creator_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.ai_plan_templates ENABLE ROW LEVEL SECURITY;

-- Policies for the new table
CREATE POLICY "Allow authenticated users to view all templates" ON public.ai_plan_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow users to insert their own templates" ON public.ai_plan_templates FOR INSERT TO authenticated WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "Allow users to update their own templates" ON public.ai_plan_templates FOR UPDATE TO authenticated USING (auth.uid() = creator_id);
CREATE POLICY "Allow users to delete their own templates" ON public.ai_plan_templates FOR DELETE TO authenticated USING (auth.uid() = creator_id);

-- Add a foreign key to ai_plans table to link to a template
ALTER TABLE public.ai_plans ADD COLUMN template_id BIGINT REFERENCES public.ai_plan_templates(id) ON DELETE SET NULL;

-- Insert a default template based on your request
INSERT INTO public.ai_plan_templates (name, creator_id, structure)
VALUES (
    'Kế hoạch Seeding Social Mặc định',
    auth.uid(),
    '[
        {"id": "goal", "label": "Mục tiêu Seeding", "type": "textarea", "icon": "Target"},
        {"id": "timeline", "label": "Thời gian triển khai", "type": "text", "icon": "Calendar"},
        {"id": "product", "label": "Sản phẩm", "type": "text", "icon": "Package"},
        {"id": "strategy", "label": "Chiến lược triển khai", "type": "textarea", "icon": "Route"},
        {
            "id": "contentDirection", 
            "label": "Định hướng Content", 
            "type": "dynamic_group", 
            "icon": "Megaphone",
            "sub_fields": [
                {"id": "serviceType", "label": "Loại dịch vụ", "type": "text"},
                {"id": "postType", "label": "Loại bài viết", "type": "text"},
                {"id": "topic", "label": "Chủ đề bài viết", "type": "text"},
                {"id": "problem", "label": "Vấn đề / Tình trạng", "type": "textarea"},
                {"id": "demo", "label": "Content Demo", "type": "textarea"},
                {"id": "commentDirection", "label": "Định hướng Comment", "type": "textarea"}
            ]
        }
    ]'::jsonb
);