-- Create seeding_logs table
CREATE TABLE public.seeding_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  post_id BIGINT NOT NULL REFERENCES public.seeding_posts(id) ON DELETE CASCADE,
  request_url TEXT,
  raw_response JSONB,
  status TEXT NOT NULL,
  error_message TEXT,
  type TEXT NOT NULL
);

-- Enable RLS
ALTER TABLE public.seeding_logs ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow access via parent post on seeding_logs"
ON public.seeding_logs
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.seeding_posts
    WHERE seeding_posts.id = seeding_logs.post_id
  )
);