-- Xóa các cột không còn sử dụng trong bảng seeding_posts
ALTER TABLE public.seeding_posts DROP COLUMN IF EXISTS is_active;
ALTER TABLE public.seeding_posts DROP COLUMN IF EXISTS check_frequency;
ALTER TABLE public.seeding_posts DROP COLUMN IF EXISTS last_checked_at;

-- Tạo bảng mới để lưu lịch trình cho mỗi dự án
CREATE TABLE public.seeding_project_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL UNIQUE REFERENCES public.seeding_projects(id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT false,
  frequency_value INT NOT NULL DEFAULT 1,
  frequency_unit TEXT NOT NULL DEFAULT 'hour', -- 'minute', 'hour', 'day'
  last_triggered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Bật RLS cho bảng mới
ALTER TABLE public.seeding_project_schedules ENABLE ROW LEVEL SECURITY;

-- Tạo chính sách bảo mật cho bảng mới
CREATE POLICY "Allow access via parent project on schedules"
ON public.seeding_project_schedules
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.seeding_projects
    WHERE seeding_projects.id = seeding_project_schedules.project_id
  )
);