-- Create table for Email Scan Logs
CREATE TABLE public.log_email_scan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  project_id BIGINT NOT NULL REFERENCES public.email_scan_projects(id) ON DELETE CASCADE,
  request_url TEXT,
  raw_response JSONB,
  status TEXT NOT NULL,
  error_message TEXT
);

-- Enable RLS for security
ALTER TABLE public.log_email_scan ENABLE ROW LEVEL SECURITY;

-- Create policies for access control
CREATE POLICY "Allow access via parent project on log_email_scan"
ON public.log_email_scan FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.email_scan_projects
    WHERE id = log_email_scan.project_id
  )
);