// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rgnqyazrhslafigptfko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnbnF5YXpyaHNsYWZpZ3B0ZmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjEyMjcsImV4cCI6MjA2NzA5NzIyN30.aq0LXZgCr0CKLsojsJZCF1feg8hNmt25h0dg8NqRweo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);